travis:
  secure:
    BINSTAR_TOKEN: KMz6utQnhC1h+yrPODCcVge0FnGWDLOnDJz1ygDzmUFsAuizN4HYcB/Xxd5R7VaFAQ/0I+z8ipa1wnF2ctTdetfwefvkvXpqLpPRWZOStukRenGc83bHQJggDULa3YCZ+dzoir4aNP+jHQfRpGOxmYN7BOx+mu3lGEmRw9iYWQW3F70tKBGavswh6dHn3Ct2KlDpKI/TGVnbJ0yWoy5MZrA3FmYXc91vBZIcV6pPCxRlvUlWLsCxEzggxl5vWA0w4FhGhx6+kDqpN4lynGpypZ2qvSalIjWq7iWqCYRusRZaxqkBRjc1KVQVvhPi4+604CV8lGQMD4lqdjlWcs0o5P3E1+P0qyeBuY2Md2gcqUkN64x11dJjKZnx5ck0DGi5i8Ye4/IrMnvTWyLZ/Vkf/ISs6xwy/XDVxwvW8zjdgl7MQbySYQ31qoE1prSShxb3Cy9OVF9oHHPAETPnVo4YN71HzB1AlBy201qkk9gaqSi1bXn18TijykhfC4GVQ2s2OZCKGQdyvyUaFQZU5ZFuVs3dfYuRNKYTCWdy9g7sR4epggBnKZ71cq2r2/5lpecJAjKDUqdhn9ZCkAKCPYvoWgwKhfxbquZfb2RoxVZWePXBNkocO2iwVnNLHQCnoCWuRpDmX20gPSqZeEsRFRBehw+s84ID5S9bHeKNhCykT7s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
