travis:
  secure:
    BINSTAR_TOKEN: LY0G6uNhD4YuLZnoAZkkhe8oaMcknUjkVP+UStGntpC0NUVrer+NVUORAPjDivFVvwJXKDWWi4PmEr87avVdCGF8XHfNj5k2HyOjXEL/qoSojFRT68JRefKWfRIDHdVfwMrFswjtDDr5gFEDo1xc8Koshcke7GPLo04WU8jEc+Nh8BlQ2Dvh3rCCGf/dwRsgLAkAUeqChIaKoZiT0h7EiRnnqrgUmnZNv8u+PIMOrDTjo2rejJhIYyLkoxCLnJplUA05SGMw4FcrEFVu5G95llAj5Kj4gM1FvHyag6taHOthLj9eUIlhOlfgKatGhVsyZfs+C/fzrkhsdcpKYHyVfKNojLBsg/jDVtOpaG9vT60LMzhYEZZHlIdCfkRCFmQLYy7WKga2Gj6sIz+2+X1zbADSbrauy5PhjXo1o4YeaMfwBdYy3a1/yh/Inal92WvqD8p6UEdNyrFuzdluZd7U9HY9I9ldjWaHZNwFO3k8UWcfhkoRb6R7jP99//29p51nkzryikwulTxg6HbJsAmKui7TamcLAFKXEguZwAt6hJAHiQf796yMAydxcDGvvzEIXssuugkb/UxAhq7lykHfX92SjvuUBAgGyjkwfZQIXYt4jUbVPn7G2xImD5L7NJl43sJoOT+aiEbnh9FgG6TNrWPqzlXZ/QEK6sOwNIlDEsI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
