travis:
  secure:
    BINSTAR_TOKEN: DMiY/os25zu+hq3zlSBGpXVJ8EEPtp+1txBKijW7Pn2TDrnNS4AwId2/FPAk5WuiYXKU+WiX0xSDiI//wOMcRjk/vJcwBoJnr2wLNw7d06kVVm6ISaLOJx6mTgkXHqPs67yVRycwy8eyxa6Cf02zehmOs7xFSNel29g8i6w3rx9PKfx1nrxG09Jqvo18arp4U7bAlYwMhqFrGi3cIklUnhd9z1hYUWbNZbF5K/It5etZIdVruKKveaG348L9pxVmMpnegXvGy2Dd2z1YF/JD5ZwXKKkJnn9rSX4nGkWkQH+FGnSNjxblTIIPqHR0MsMtJw+UiiKFvl5ZmAYljNSksLyvKtkWZ1/cvj6lFILtDMqtlZgwVVF5RRFKpcgdIhkOafnjQbXezjZ5LLbzcx6qwRgmR1Exmufd+NP4ldE2SN7/bVp9wFDalyCs8optPSwlyXNxybm01nVS+xefv1KnIfqOm/Sgrp2Qkg7qxNGo5cWS9xMVSkBadYOXVjcq/woVhm7LxXnelh0wK7/UzyHGqBlvuT9/bkFbtok0r0nlzF5EsgYEA8oDh4ZwiPXNPqm5onoJ6wDKMjheMuyXFkQdCeeDaQercpoDRjbj4mSK0x8OuPRvZ2X1nTOlU5Pe2qir1apRoGZpGvdk/azZiGv13kNPVa8mJtzyJFmX5nUC3xs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
