travis:
  secure:
    BINSTAR_TOKEN: Bxr+Yf7fdLOQWOUruxyGCVbcB/MPOJFEACQ1Zn+3LV1i8iCA1ntc0yljuSgbDiZ/df18ecwjP9A8lJ4Z3/8NLSe5JQ0DiiCZzmhpP0bnEDRfGkrFd4RomV8lP1/k0z70jXoRy4ah22HxiwT0575UQRBSF57+Vmt6Qx7EzcWMfDNTzezhFZr8Js86TO/9kUhGmAVKA7HKf+ApgPp8tnhWo/GXHq26ex7radCtHhedtL+611NqF7hlA8gCAXs8K/dfXRz/mTI8DB/sH35DA6ZAVWtVfrAwc6DYE1wGo3kf0gX0Hg3BFnU32ckiu/gOL1ZmhKpTTZNRXU+UhxvX3dAjRphCIASlZiEXYgW0p7kAYTCItVZp63lBrmDIAB2LxEmcIflKHZHdWGwUWQVmZ3gZdDlQtfGmVhHS1zdA6b62qDMGHAZlPzNrAYTC0s7tr/eXBUYus2TUp3bgdLz0jpA+hfA50d8EBau1OAGmBCYugPjdNvtEsWdfDwozMupXrwStIB8Xc8WFxRL+OnlacUQ9pMDkDFKGDToVutC1z6yxKI6rBLczBOoOzwJ1wPhCkAKUB66iocs7v+cKRNThP7tz5i1juBys5nJXIxH/nfL+ENeR+MCldYVf9vAxolvQwQx2qM5at/rOFdNE/Vx96bZTftG9D+y+U2gWTCUnNV7kwuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
