travis:
  secure:
    BINSTAR_TOKEN: d+Xz9vevxRDk/BB2kxxq0mr4WU+fmXexC6H4IA14XN3z3bUoSSTgmLf1uFsQqLFK7w/JUQbQ1E2n5hY4c9X70S5UJLs5JjZXD/nmGPStoHJlZ8/pwhGqHiQU0mkcW7JBHIRRqQXkmbzJEAn51H9fjtfC9FrxYoxJtaHzoSdmaFsgo0MZTy6x+o48NCZLWldWXIz0JmpnVTCywDmLqtQgNzqrtCmDLkzVirN1EQ6yHwjmJbC3TtfgDoJQPhM2qsEokf/cRqd2TCe4CQ0M8l+BirqaoG2nXbcSy9fvKVGUvqo9LHuXu0PCqc4TwErha+NoU7Xx95u0avKi4lTUuGL3HIZ64JwqpXUXN5VEphtQp/HJFIbyCFbb+LQVzJgq44qMlRUawmV/VzWpSGvEGPWMyKV8VfkLqdMvFYC/hyE0In7IvCwb4+IAPP7g9C84XvM8ZK9jOdW3ChjV+y+YfO8f056Xz/jpPJlcppQYQeXQ2OPfe4WCIo+tjbv4UzPQ0GBTcJLvHmHrKJIlYESUhRXIdq/Yt9hvEnB9SrbHgP2vRRcy+Khbo1EWx3qZP/u3fPZJkrOQczpSSRbD5CVtFM6vAOvCdYblNoKDV62hLGiU7sMSlyyWx/DzHUvt6bZvMA/zt67kSNKe6In+mQNrofuTBIXL9nvKinMySNgWlXFOTzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
